config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/index'

  get 'pages/about'

  get 'pages/x'

  get 'pages/guardar_cliente'

  post 'pages/guardar_auto'

  root 'pages#home'

end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@nombre_completo = params[:nombre_completo]
  	@correo_electronico = params[:correo_electronico]
  	@edad_usuario = params[:edad_usuario]
    @clientes = Client.all
  end

  def index
  end

  def about
  end

  def x
    @aut = Auto.all
  end

  def guardar_cliente
    @nombre_completo = params[:nombre_completo]
    @correo_electronico = params[:correo_electronico]
    @edad_usuario = params[:edad_usuario]

    unless @nombre_completo.blank?
      Client.create({
        name: @nombre_completo,
        email: @correo_electronico,
        edad: @edad_usuario
      })
    end

    redirect_to pages_home_path
  end

  def guardar_auto
    @modelo = params[:modelo]
    @marca = params[:marca]
    @kilometros = params[:kilometros]
      unless @modelo.blank?
      Auto.create({
        modelo: @modelo,
        marca: @marca,
        km: @kilometros
      })
    end
    redirect_to pages_x_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clase42taller</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>
<!-- <a href="<%= pages_home_path %>">Home</a>
<a href="<%= pages_about_path %>">About</a>
<a href="<%= pages_index_path %>">Index</a>
<a href="<%= pages_x_path %>">Carros</a> -->
	<%= yield %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1 class="text-uppercase text-center">Jose Daniel Lopez</h1>
<p>Bienvenido, registrate</p>

<%= params %>
<div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<form method="get" action="<%= pages_guardar_cliente_path %>">
		  <div class="form-group">
		    <label for="nombre_completo">Introduzca su numbre:</label>
		    <input type="text" class="form-control" name="nombre_completo" id="nombre_completo" placeholder="Nombre" >
		  </div>
		  <div class="form-group">
		    <label for="correo_electronico">Email:</label>
		    <input type="email" class="form-control" name ="correo_electronico" id="correo_electronico" placeholder="example@correo.com">
		  </div>
		  <div class="form-group">
		    <label for="edad_usuario">Introduzca la edad:</label>
		    <input type="number" value="18" name="edad_usuario" id="edad_usuario" min="10" max="70" >
		  </div>
		  <button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
</div>

<% @clientes.each do |u| %>
	<p><%= u.id %> <%= u.name %> <%= u.edad %> <%= u.email %></p>
<!-- 	<p><%= u.name %></p>
	<p><%= u.edad %></p>
	<p><%= u.created_at %></p> -->
	<p>_______________________</p>
<% end -%>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Creative - Start Bootstrap Theme</title>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Custom Fonts -->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Services</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Your Favorite Source of Free Bootstrap Themes</h1>
                <hr>
                <p>Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                    <a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond text-primary sr-icons"></i>
                        <h3>Sturdy Templates</h3>
                        <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane text-primary sr-icons"></i>
                        <h3>Ready to Ship</h3>
                        <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o text-primary sr-icons"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">We update dependencies to keep things fresh.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart text-primary sr-icons"></i>
                        <h3>Made with Love</h3>
                        <p class="text-muted">You have to make your websites with love these days!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter popup-gallery">
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/1' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/1' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/2' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/2' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/3' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/3' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/4' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/4' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/5' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/5' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="<%= asset_path 'fullsize/6' %>" class="portfolio-box">
                        <img src="<%= asset_path 'thumbnails/6' %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="http://startbootstrap.com/template-overviews/creative/" class="btn btn-default btn-xl sr-button">Download Now!</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
 <!--    <script src="vendor/jquery/jquery.min.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
   <!--  <script src="vendor/bootstrap/js/bootstrap.min.js"></script> -->

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<!--     <script src="vendor/scrollreveal/scrollreveal.min.js"></script> -->
<!--     <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script> -->

    <!-- Theme JavaScript -->
 <!--    <script src="js/creative.min.js"></script> -->

</body>

</html>

app/views/pages/x.html.erb
<h1>GUARDA LA INFO DE TU CARRO</h1>
<p>YO VOY POR POST</p>

<div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<form method="post" action="<%= pages_guardar_auto_path %>">
		  <div class="form-group">
		    <label for="modelo">Introduzca su modelo</label>
		    <input type="text" class="form-control" name="modelo" id="modelo" placeholder="Modelo" >
		  </div>
		  <div class="form-group">
		    <label for="marca">Marca:</label>
		    <input type="text" class="form-control" name ="marca" id="marca" placeholder="example@correo.com">
		  </div>
		  <div class="form-group">
		    <label for="kilometros">Introduzca el kilometraje:</label>
		    <input type="number" value="0" name="kilometros" id="kilometros" min="0" max="700000" >
		  </div>
		  <input type="hidden" 
       value="<%= form_authenticity_token() %>" 
       name="authenticity_token"/>
		  <button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
</div>
<% @aut.each do |u| %>
	<p><%= u.id %> <%= u.modelo %> <%= u.marca %> <%= u.km %></p>
	<p>_______________________</p>
<% end -%>